// Fox v0.5
// by Jaroslaw Rozynski
//===
// TODO:


#define FOX_PROC_UNUSED(ret,func,params)
FOX_PROC_UNUSED(void,glAccum,(GLenum,GLfloat))
FOX_PROC_UNUSED(void,glAlphaFunc,(GLenum,GLclampf))
FOX_PROC_UNUSED(GLboolean,glAreTexturesResident,(GLsizei,const GLuint*,GLboolean*))
FOX_PROC_UNUSED(void,glArrayElement,(GLint))
FOX_PROC(void,glBegin,(GLenum))
FOX_PROC(void,glBindTexture,(GLenum,GLuint))
FOX_PROC_UNUSED(void,glBitmap,(GLsizei,GLsizei,GLfloat,GLfloat,GLfloat,GLfloat,const GLubyte*))
FOX_PROC(void,glBlendFunc,(GLenum,GLenum))
FOX_PROC_UNUSED(void,glCallList,(GLuint))
FOX_PROC_UNUSED(void,glCallLists,(GLsizei,GLenum,const GLvoid*))
FOX_PROC_UNUSED(void,glClear,(GLbitfield))
FOX_PROC_UNUSED(void,glClearAccum,(GLfloat,GLfloat,GLfloat,GLfloat))
FOX_PROC_UNUSED(void,glClearColor,(GLclampf,GLclampf,GLclampf,GLclampf))
FOX_PROC_UNUSED(void,glClearDepth,(GLclampd))
FOX_PROC_UNUSED(void,glClearIndex,(GLfloat))
FOX_PROC_UNUSED(void,glClearStencil,(GLint))
FOX_PROC_UNUSED(void,glClipPlane,(GLenum,const GLdouble*))
FOX_PROC_UNUSED(void,glColor3b,(GLbyte,GLbyte,GLbyte))
FOX_PROC_UNUSED(void,glColor3bv,(const GLbyte*))
FOX_PROC_UNUSED(void,glColor3d,(GLdouble,GLdouble,GLdouble))
FOX_PROC_UNUSED(void,glColor3dv,(const GLdouble*))
FOX_PROC_UNUSED(void,glColor3f,(GLfloat,GLfloat,GLfloat))
FOX_PROC_UNUSED(void,glColor3fv,(const GLfloat*))
FOX_PROC_UNUSED(void,glColor3i,(GLint,GLint,GLint))
FOX_PROC_UNUSED(void,glColor3iv,(const GLint*))
FOX_PROC_UNUSED(void,glColor3s,(GLshort,GLshort,GLshort))
FOX_PROC_UNUSED(void,glColor3sv,(const GLshort*))
FOX_PROC_UNUSED(void,glColor3ub,(GLubyte,GLubyte,GLubyte))
FOX_PROC_UNUSED(void,glColor3ubv,(const GLubyte*))
FOX_PROC_UNUSED(void,glColor3ui,(GLuint,GLuint,GLuint))
FOX_PROC_UNUSED(void,glColor3uiv,(const GLuint*))
FOX_PROC_UNUSED(void,glColor3us,(GLushort,GLushort,GLushort))
FOX_PROC_UNUSED(void,glColor3usv,(const GLushort*))
FOX_PROC_UNUSED(void,glColor4b,(GLbyte,GLbyte,GLbyte,GLbyte))
FOX_PROC_UNUSED(void,glColor4bv,(const GLbyte*))
FOX_PROC_UNUSED(void,glColor4d,(GLdouble,GLdouble,GLdouble,GLdouble))
FOX_PROC_UNUSED(void,glColor4dv,(const GLdouble*))
FOX_PROC(void,glColor4f,(GLfloat,GLfloat,GLfloat,GLfloat))
FOX_PROC_UNUSED(void,glColor4fv,(const GLfloat*))
FOX_PROC_UNUSED(void,glColor4i,(GLint,GLint,GLint,GLint))
FOX_PROC_UNUSED(void,glColor4iv,(const GLint*))
FOX_PROC_UNUSED(void,glColor4s,(GLshort,GLshort,GLshort,GLshort))
FOX_PROC_UNUSED(void,glColor4sv,(const GLshort*))
FOX_PROC_UNUSED(void,glColor4ub,(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
FOX_PROC_UNUSED(void,glColor4ubv,(const GLubyte *v))
FOX_PROC_UNUSED(void,glColor4ui,(GLuint red, GLuint green, GLuint blue, GLuint alpha))
FOX_PROC_UNUSED(void,glColor4uiv,(const GLuint *v))
FOX_PROC_UNUSED(void,glColor4us,(GLushort red, GLushort green, GLushort blue, GLushort alpha))
FOX_PROC_UNUSED(void,glColor4usv,(const GLushort *v))
FOX_PROC_UNUSED(void,glColorMask,(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
FOX_PROC_UNUSED(void,glColorMaterial,(GLenum face, GLenum mode))
FOX_PROC_UNUSED(void,glColorPointer,(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))
FOX_PROC_UNUSED(void,glCopyPixels,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type))
FOX_PROC(void,glCopyTexImage1D,(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border))
FOX_PROC_UNUSED(void,glCopyTexImage2D,(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
FOX_PROC_UNUSED(void,glCopyTexSubImage1D,(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width))
FOX_PROC_UNUSED(void,glCopyTexSubImage2D,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
FOX_PROC_UNUSED(void,glCullFace,(GLenum mode))
FOX_PROC_UNUSED(void,glDeleteLists,(GLuint list, GLsizei range))
FOX_PROC_UNUSED(void,glDeleteTextures,(GLsizei n, const GLuint *textures))
FOX_PROC_UNUSED(void,glDepthFunc,(GLenum func))
FOX_PROC_UNUSED(void,glDepthMask,(GLboolean flag))
FOX_PROC_UNUSED(void,glDepthRange,(GLclampd zNear, GLclampd zFar))
FOX_PROC(void,glDisable,(GLenum cap))
FOX_PROC_UNUSED(void,glDisableClientState,(GLenum array))
FOX_PROC_UNUSED(void,glDrawArrays,(GLenum mode, GLint first, GLsizei count))
FOX_PROC_UNUSED(void,glDrawBuffer,(GLenum mode))
FOX_PROC_UNUSED(void,glDrawElements,(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices))
FOX_PROC_UNUSED(void,glDrawPixels,(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))
FOX_PROC_UNUSED(void,glEdgeFlag,(GLboolean flag))
FOX_PROC_UNUSED(void,glEdgeFlagPointer,(GLsizei stride, const GLvoid *pointer))
FOX_PROC_UNUSED(void,glEdgeFlagv,(const GLboolean *flag))
FOX_PROC(void,glEnable,(GLenum cap))
FOX_PROC_UNUSED(void,glEnableClientState,(GLenum array))
FOX_PROC(void,glEnd,(void))
FOX_PROC_UNUSED(void,glEndList,(void))
FOX_PROC_UNUSED(void,glEvalCoord1d,(GLdouble u))
FOX_PROC_UNUSED(void,glEvalCoord1dv,(const GLdouble *u))
FOX_PROC_UNUSED(void,glEvalCoord1f,(GLfloat u))
FOX_PROC_UNUSED(void,glEvalCoord1fv,(const GLfloat *u))
FOX_PROC_UNUSED(void,glEvalCoord2d,(GLdouble u, GLdouble v))
FOX_PROC_UNUSED(void,glEvalCoord2dv,(const GLdouble *u))
FOX_PROC_UNUSED(void,glEvalCoord2f,(GLfloat u, GLfloat v))
FOX_PROC_UNUSED(void,glEvalCoord2fv,(const GLfloat *u))
FOX_PROC_UNUSED(void,glEvalMesh1,(GLenum mode, GLint i1, GLint i2))
FOX_PROC_UNUSED(void,glEvalMesh2,(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2))
FOX_PROC_UNUSED(void,glEvalPoint1,(GLint i))
FOX_PROC_UNUSED(void,glEvalPoint2,(GLint i, GLint j))
FOX_PROC_UNUSED(void,glFeedbackBuffer,(GLsizei size, GLenum type, GLfloat *buffer))
FOX_PROC_UNUSED(void,glFinish,(void))
FOX_PROC(void,glFlush,(void))
FOX_PROC_UNUSED(void,glFogf,(GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glFogfv,(GLenum pname, const GLfloat *params))
FOX_PROC_UNUSED(void,glFogi,(GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glFogiv,(GLenum pname, const GLint *params))
FOX_PROC_UNUSED(void,glFrontFace,(GLenum mode))
FOX_PROC_UNUSED(void,glFrustum,(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
FOX_PROC_UNUSED(GLuint,glGenLists,(GLsizei range))
FOX_PROC(void,glGenTextures,(GLsizei n, GLuint *textures))
FOX_PROC_UNUSED(void,glGetBooleanv,(GLenum pname, GLboolean *params))
FOX_PROC_UNUSED(void,glGetClipPlane,(GLenum plane, GLdouble *equation))
FOX_PROC_UNUSED(void,glGetDoublev,(GLenum pname, GLdouble *params))
FOX_PROC_UNUSED(GLenum,glGetError,(void))
FOX_PROC_UNUSED(void,glGetFloatv,(GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetIntegerv,(GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glGetLightfv,(GLenum light, GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetLightiv,(GLenum light, GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glGetMapdv,(GLenum target, GLenum query, GLdouble *v))
FOX_PROC_UNUSED(void,glGetMapfv,(GLenum target, GLenum query, GLfloat *v))
FOX_PROC_UNUSED(void,glGetMapiv,(GLenum target, GLenum query, GLint *v))
FOX_PROC_UNUSED(void,glGetMaterialfv,(GLenum face, GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetMaterialiv,(GLenum face, GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glGetPixelMapfv,(GLenum map, GLfloat *values))
FOX_PROC_UNUSED(void,glGetPixelMapuiv,(GLenum map, GLuint *values))
FOX_PROC_UNUSED(void,glGetPixelMapusv,(GLenum map, GLushort *values))
FOX_PROC_UNUSED(void,glGetPointerv,(GLenum pname, GLvoid* *params))
FOX_PROC_UNUSED(void,glGetPolygonStipple,(GLubyte *mask))
FOX_PROC(const GLubyte *,glGetString,(GLenum name))
FOX_PROC_UNUSED(void,glGetTexEnvfv,(GLenum target, GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetTexEnviv,(GLenum target, GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glGetTexGendv,(GLenum coord, GLenum pname, GLdouble *params))
FOX_PROC_UNUSED(void,glGetTexGenfv,(GLenum coord, GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetTexGeniv,(GLenum coord, GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glGetTexImage,(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels))
FOX_PROC_UNUSED(void,glGetTexLevelParameterfv,(GLenum target, GLint level, GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetTexLevelParameteriv,(GLenum target, GLint level, GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glGetTexParameterfv,(GLenum target, GLenum pname, GLfloat *params))
FOX_PROC_UNUSED(void,glGetTexParameteriv,(GLenum target, GLenum pname, GLint *params))
FOX_PROC_UNUSED(void,glHint,(GLenum target, GLenum mode))
FOX_PROC_UNUSED(void,glIndexMask,(GLuint mask))
FOX_PROC_UNUSED(void,glIndexPointer,(GLenum type, GLsizei stride, const GLvoid *pointer))
FOX_PROC_UNUSED(void,glIndexd,(GLdouble c))
FOX_PROC_UNUSED(void,glIndexdv,(const GLdouble *c))
FOX_PROC_UNUSED(void,glIndexf,(GLfloat c))
FOX_PROC_UNUSED(void,glIndexfv,(const GLfloat *c))
FOX_PROC_UNUSED(void,glIndexi,(GLint c))
FOX_PROC_UNUSED(void,glIndexiv,(const GLint *c))
FOX_PROC_UNUSED(void,glIndexs,(GLshort c))
FOX_PROC_UNUSED(void,glIndexsv,(const GLshort *c))
FOX_PROC_UNUSED(void,glIndexub,(GLubyte c))
FOX_PROC_UNUSED(void,glIndexubv,(const GLubyte *c))
FOX_PROC_UNUSED(void,glInitNames,(void))
FOX_PROC_UNUSED(void,glInterleavedArrays,(GLenum format, GLsizei stride, const GLvoid *pointer))
FOX_PROC_UNUSED(GLboolean,glIsEnabled,(GLenum cap))
FOX_PROC_UNUSED(GLboolean,glIsList,(GLuint list))
FOX_PROC_UNUSED(GLboolean,glIsTexture,(GLuint texture))
FOX_PROC_UNUSED(void,glLightModelf,(GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glLightModelfv,(GLenum pname, const GLfloat *params))
FOX_PROC_UNUSED(void,glLightModeli,(GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glLightModeliv,(GLenum pname, const GLint *params))
FOX_PROC_UNUSED(void,glLightf,(GLenum light, GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glLightfv,(GLenum light, GLenum pname, const GLfloat *params))
FOX_PROC_UNUSED(void,glLighti,(GLenum light, GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glLightiv,(GLenum light, GLenum pname, const GLint *params))
FOX_PROC_UNUSED(void,glLineStipple,(GLint factor, GLushort pattern))
FOX_PROC_UNUSED(void,glLineWidth,(GLfloat width))
FOX_PROC_UNUSED(void,glListBase,(GLuint base))
FOX_PROC(void,glLoadIdentity,(void))
FOX_PROC_UNUSED(void,glLoadMatrixd,(const GLdouble *m))
FOX_PROC_UNUSED(void,glLoadMatrixf,(const GLfloat *m))
FOX_PROC_UNUSED(void,glLoadName,(GLuint name))
FOX_PROC_UNUSED(void,glLogicOp,(GLenum opcode))
FOX_PROC_UNUSED(void,glMap1d,(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points))
FOX_PROC_UNUSED(void,glMap1f,(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points))
FOX_PROC_UNUSED(void,glMap2d,(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points))
FOX_PROC_UNUSED(void,glMap2f,(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points))
FOX_PROC_UNUSED(void,glMapGrid1d,(GLint un, GLdouble u1, GLdouble u2))
FOX_PROC_UNUSED(void,glMapGrid1f,(GLint un, GLfloat u1, GLfloat u2))
FOX_PROC_UNUSED(void,glMapGrid2d,(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2))
FOX_PROC_UNUSED(void,glMapGrid2f,(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2))
FOX_PROC_UNUSED(void,glMaterialf,(GLenum face, GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glMaterialfv,(GLenum face, GLenum pname, const GLfloat *params))
FOX_PROC_UNUSED(void,glMateriali,(GLenum face, GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glMaterialiv,(GLenum face, GLenum pname, const GLint *params))
FOX_PROC(void,glMatrixMode,(GLenum mode))
FOX_PROC_UNUSED(void,glMultMatrixd,(const GLdouble *m))
FOX_PROC_UNUSED(void,glMultMatrixf,(const GLfloat *m))
FOX_PROC_UNUSED(void,glNewList,(GLuint list, GLenum mode))
FOX_PROC_UNUSED(void,glNormal3b,(GLbyte nx, GLbyte ny, GLbyte nz))
FOX_PROC_UNUSED(void,glNormal3bv,(const GLbyte *v))
FOX_PROC_UNUSED(void,glNormal3d,(GLdouble nx, GLdouble ny, GLdouble nz))
FOX_PROC_UNUSED(void,glNormal3dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glNormal3f,(GLfloat nx, GLfloat ny, GLfloat nz))
FOX_PROC_UNUSED(void,glNormal3fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glNormal3i,(GLint nx, GLint ny, GLint nz))
FOX_PROC_UNUSED(void,glNormal3iv,(const GLint *v))
FOX_PROC_UNUSED(void,glNormal3s,(GLshort nx, GLshort ny, GLshort nz))
FOX_PROC_UNUSED(void,glNormal3sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glNormalPointer,(GLenum type, GLsizei stride, const GLvoid *pointer))
FOX_PROC(void,glOrtho,(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
FOX_PROC_UNUSED(void,glPassThrough,(GLfloat token))
FOX_PROC_UNUSED(void,glPixelMapfv,(GLenum map, GLsizei mapsize, const GLfloat *values))
FOX_PROC_UNUSED(void,glPixelMapuiv,(GLenum map, GLsizei mapsize, const GLuint *values))
FOX_PROC_UNUSED(void,glPixelMapusv,(GLenum map, GLsizei mapsize, const GLushort *values))
FOX_PROC_UNUSED(void,glPixelStoref,(GLenum pname, GLfloat param))
FOX_PROC(void,glPixelStorei,(GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glPixelTransferf,(GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glPixelTransferi,(GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glPixelZoom,(GLfloat xfactor, GLfloat yfactor))
FOX_PROC_UNUSED(void,glPointSize,(GLfloat size))
FOX_PROC_UNUSED(void,glPolygonMode,(GLenum face, GLenum mode))
FOX_PROC_UNUSED(void,glPolygonOffset,(GLfloat factor, GLfloat units))
FOX_PROC_UNUSED(void,glPolygonStipple,(const GLubyte *mask))
FOX_PROC(void,glPopAttrib,(void))
FOX_PROC(void,glPopClientAttrib,(void))
FOX_PROC(void,glPopMatrix,(void))
FOX_PROC_UNUSED(void,glPopName,(void))
FOX_PROC_UNUSED(void,glPrioritizeTextures,(GLsizei n, const GLuint *textures, const GLclampf *priorities))
FOX_PROC(void,glPushAttrib,(GLbitfield mask))
FOX_PROC(void,glPushClientAttrib,(GLbitfield mask))
FOX_PROC(void,glPushMatrix,(void))
FOX_PROC_UNUSED(void,glPushName,(GLuint name))
FOX_PROC_UNUSED(void,glRasterPos2d,(GLdouble x, GLdouble y))
FOX_PROC_UNUSED(void,glRasterPos2dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glRasterPos2f,(GLfloat x, GLfloat y))
FOX_PROC_UNUSED(void,glRasterPos2fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glRasterPos2i,(GLint x, GLint y))
FOX_PROC_UNUSED(void,glRasterPos2iv,(const GLint *v))
FOX_PROC_UNUSED(void,glRasterPos2s,(GLshort x, GLshort y))
FOX_PROC_UNUSED(void,glRasterPos2sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glRasterPos3d,(GLdouble x, GLdouble y, GLdouble z))
FOX_PROC_UNUSED(void,glRasterPos3dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glRasterPos3f,(GLfloat x, GLfloat y, GLfloat z))
FOX_PROC_UNUSED(void,glRasterPos3fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glRasterPos3i,(GLint x, GLint y, GLint z))
FOX_PROC_UNUSED(void,glRasterPos3iv,(const GLint *v))
FOX_PROC_UNUSED(void,glRasterPos3s,(GLshort x, GLshort y, GLshort z))
FOX_PROC_UNUSED(void,glRasterPos3sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glRasterPos4d,(GLdouble x, GLdouble y, GLdouble z, GLdouble w))
FOX_PROC_UNUSED(void,glRasterPos4dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glRasterPos4f,(GLfloat x, GLfloat y, GLfloat z, GLfloat w))
FOX_PROC_UNUSED(void,glRasterPos4fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glRasterPos4i,(GLint x, GLint y, GLint z, GLint w))
FOX_PROC_UNUSED(void,glRasterPos4iv,(const GLint *v))
FOX_PROC_UNUSED(void,glRasterPos4s,(GLshort x, GLshort y, GLshort z, GLshort w))
FOX_PROC_UNUSED(void,glRasterPos4sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glReadBuffer,(GLenum mode))
FOX_PROC_UNUSED(void,glReadPixels,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels))
FOX_PROC_UNUSED(void,glRectd,(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2))
FOX_PROC_UNUSED(void,glRectdv,(const GLdouble *v1, const GLdouble *v2))
FOX_PROC_UNUSED(void,glRectf,(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2))
FOX_PROC_UNUSED(void,glRectfv,(const GLfloat *v1, const GLfloat *v2))
FOX_PROC_UNUSED(void,glRecti,(GLint x1, GLint y1, GLint x2, GLint y2))
FOX_PROC_UNUSED(void,glRectiv,(const GLint *v1, const GLint *v2))
FOX_PROC_UNUSED(void,glRects,(GLshort x1, GLshort y1, GLshort x2, GLshort y2))
FOX_PROC_UNUSED(void,glRectsv,(const GLshort *v1, const GLshort *v2))
FOX_PROC_UNUSED(GLint,glRenderMode,(GLenum mode))
FOX_PROC_UNUSED(void,glRotated,(GLdouble angle, GLdouble x, GLdouble y, GLdouble z))
FOX_PROC_UNUSED(void,glRotatef,(GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
FOX_PROC_UNUSED(void,glScaled,(GLdouble x, GLdouble y, GLdouble z))
FOX_PROC_UNUSED(void,glScalef,(GLfloat x, GLfloat y, GLfloat z))
FOX_PROC_UNUSED(void,glScissor,(GLint x, GLint y, GLsizei width, GLsizei height))
FOX_PROC_UNUSED(void,glSelectBuffer,(GLsizei size, GLuint *buffer))
FOX_PROC_UNUSED(void,glShadeModel,(GLenum mode))
FOX_PROC_UNUSED(void,glStencilFunc,(GLenum func, GLint ref, GLuint mask))
FOX_PROC_UNUSED(void,glStencilMask,(GLuint mask))
FOX_PROC_UNUSED(void,glStencilOp,(GLenum fail, GLenum zfail, GLenum zpass))
FOX_PROC_UNUSED(void,glTexCoord1d,(GLdouble s))
FOX_PROC_UNUSED(void,glTexCoord1dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glTexCoord1f,(GLfloat s))
FOX_PROC_UNUSED(void,glTexCoord1fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glTexCoord1i,(GLint s))
FOX_PROC_UNUSED(void,glTexCoord1iv,(const GLint *v))
FOX_PROC_UNUSED(void,glTexCoord1s,(GLshort s))
FOX_PROC_UNUSED(void,glTexCoord1sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glTexCoord2d,(GLdouble s, GLdouble t))
FOX_PROC_UNUSED(void,glTexCoord2dv,(const GLdouble *v))
FOX_PROC(void,glTexCoord2f,(GLfloat s, GLfloat t))
FOX_PROC_UNUSED(void,glTexCoord2fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glTexCoord2i,(GLint s, GLint t))
FOX_PROC_UNUSED(void,glTexCoord2iv,(const GLint *v))
FOX_PROC_UNUSED(void,glTexCoord2s,(GLshort s, GLshort t))
FOX_PROC_UNUSED(void,glTexCoord2sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glTexCoord3d,(GLdouble s, GLdouble t, GLdouble r))
FOX_PROC_UNUSED(void,glTexCoord3dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glTexCoord3f,(GLfloat s, GLfloat t, GLfloat r))
FOX_PROC_UNUSED(void,glTexCoord3fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glTexCoord3i,(GLint s, GLint t, GLint r))
FOX_PROC_UNUSED(void,glTexCoord3iv,(const GLint *v))
FOX_PROC_UNUSED(void,glTexCoord3s,(GLshort s, GLshort t, GLshort r))
FOX_PROC_UNUSED(void,glTexCoord3sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glTexCoord4d,(GLdouble s, GLdouble t, GLdouble r, GLdouble q))
FOX_PROC_UNUSED(void,glTexCoord4dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glTexCoord4f,(GLfloat s, GLfloat t, GLfloat r, GLfloat q))
FOX_PROC_UNUSED(void,glTexCoord4fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glTexCoord4i,(GLint s, GLint t, GLint r, GLint q))
FOX_PROC_UNUSED(void,glTexCoord4iv,(const GLint *v))
FOX_PROC_UNUSED(void,glTexCoord4s,(GLshort s, GLshort t, GLshort r, GLshort q))
FOX_PROC_UNUSED(void,glTexCoord4sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glTexCoordPointer,(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))
FOX_PROC(void,glTexEnvf,(GLenum target, GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glTexEnvfv,(GLenum target, GLenum pname, const GLfloat *params))
FOX_PROC_UNUSED(void,glTexEnvi,(GLenum target, GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glTexEnviv,(GLenum target, GLenum pname, const GLint *params))
FOX_PROC_UNUSED(void,glTexGend,(GLenum coord, GLenum pname, GLdouble param))
FOX_PROC_UNUSED(void,glTexGendv,(GLenum coord, GLenum pname, const GLdouble *params))
FOX_PROC_UNUSED(void,glTexGenf,(GLenum coord, GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glTexGenfv,(GLenum coord, GLenum pname, const GLfloat *params))
FOX_PROC_UNUSED(void,glTexGeni,(GLenum coord, GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glTexGeniv,(GLenum coord, GLenum pname, const GLint *params))
FOX_PROC_UNUSED(void,glTexImage1D,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
FOX_PROC(void,glTexImage2D,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
FOX_PROC_UNUSED(void,glTexParameterf,(GLenum target, GLenum pname, GLfloat param))
FOX_PROC_UNUSED(void,glTexParameterfv,(GLenum target, GLenum pname, const GLfloat *params))
FOX_PROC(void,glTexParameteri,(GLenum target, GLenum pname, GLint param))
FOX_PROC_UNUSED(void,glTexParameteriv,(GLenum target, GLenum pname, const GLint *params))
FOX_PROC_UNUSED(void,glTexSubImage1D,(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels))
FOX_PROC(void,glTexSubImage2D,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))
FOX_PROC_UNUSED(void,glTranslated,(GLdouble x, GLdouble y, GLdouble z))
FOX_PROC_UNUSED(void,glTranslatef,(GLfloat x, GLfloat y, GLfloat z))
FOX_PROC_UNUSED(void,glVertex2d,(GLdouble x, GLdouble y))
FOX_PROC_UNUSED(void,glVertex2dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glVertex2f,(GLfloat x, GLfloat y))
FOX_PROC_UNUSED(void,glVertex2fv,(const GLfloat *v))
FOX_PROC(void,glVertex2i,(GLint x, GLint y))
FOX_PROC_UNUSED(void,glVertex2iv,(const GLint *v))
FOX_PROC_UNUSED(void,glVertex2s,(GLshort x, GLshort y))
FOX_PROC_UNUSED(void,glVertex2sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glVertex3d,(GLdouble x, GLdouble y, GLdouble z))
FOX_PROC_UNUSED(void,glVertex3dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glVertex3f,(GLfloat x, GLfloat y, GLfloat z))
FOX_PROC_UNUSED(void,glVertex3fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glVertex3i,(GLint x, GLint y, GLint z))
FOX_PROC_UNUSED(void,glVertex3iv,(const GLint *v))
FOX_PROC_UNUSED(void,glVertex3s,(GLshort x, GLshort y, GLshort z))
FOX_PROC_UNUSED(void,glVertex3sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glVertex4d,(GLdouble x, GLdouble y, GLdouble z, GLdouble w))
FOX_PROC_UNUSED(void,glVertex4dv,(const GLdouble *v))
FOX_PROC_UNUSED(void,glVertex4f,(GLfloat x, GLfloat y, GLfloat z, GLfloat w))
FOX_PROC_UNUSED(void,glVertex4fv,(const GLfloat *v))
FOX_PROC_UNUSED(void,glVertex4i,(GLint x, GLint y, GLint z, GLint w))
FOX_PROC_UNUSED(void,glVertex4iv,(const GLint *v))
FOX_PROC_UNUSED(void,glVertex4s,(GLshort x, GLshort y, GLshort z, GLshort w))
FOX_PROC_UNUSED(void,glVertex4sv,(const GLshort *v))
FOX_PROC_UNUSED(void,glVertexPointer,(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))
FOX_PROC(void,glViewport,(GLint x, GLint y, GLsizei width, GLsizei height))

// end
